# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['Diamante-Clicker-Universal.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('auto_zoom.py', '.'),
    ],
    hiddenimports=[
        'pynput',
        'pynput.mouse',
        'pynput.mouse._win32',
        'pynput.keyboard',
        'pynput.keyboard._win32',
        'pynput._util',
        'pynput._util.win32',
        'cv2',
        'numpy',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'pyautogui',
        'tkinter',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'json',
        'threading',
        're',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Diamante-Clicker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
)
